=== paparazzi/paparazzi/conf/airframes/airframe.dtd
<!-- Paparazzi airframe DTD -->

<!ELEMENT airframe (include|servos|commands|rc_commands|auto_rc_commands|ap_only_commands|command_laws|section|modules|firmware|autopilot|heli_curves|description|checklist)*>
<!ELEMENT include EMPTY>
<!ELEMENT servos (servo)*>
<!ELEMENT commands (axis)*>
<!ELEMENT rc_commands (set)*>
<!ELEMENT auto_rc_commands (set)*>
<!ELEMENT ap_only_commands (copy)*>
<!ELEMENT command_laws (let|set|call|ratelimit)*>
<!ELEMENT heli_curves (curve)*>
<!ELEMENT section (define|comment)*>
<!ELEMENT servo EMPTY>
<!ELEMENT axis EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT ratelimit EMPTY>
<!ELEMENT copy EMPTY>
<!ELEMENT curve EMPTY>
<!ELEMENT let EMPTY>
<!ELEMENT define (field)*>
<!ELEMENT field (field)*>
<!ELEMENT modules (module)*>
<!ELEMENT configure EMPTY>
<!ELEMENT firmware (target|module|autopilot|configure|define|comment)*>
<!ELEMENT target (module|autopilot|configure|define|comment)*>
<!ELEMENT module (configure|define|comment)*>
<!ELEMENT autopilot EMPTY>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT checklist (item)*>

<!ATTLIST include
href CDATA #REQUIRED>

<!ATTLIST firmware
name CDATA #REQUIRED>

<!ATTLIST autopilot
name CDATA #REQUIRED
freq CDATA #IMPLIED>

<!ATTLIST target
name CDATA #REQUIRED
board CDATA #REQUIRED>

<!ATTLIST airframe
name CDATA #IMPLIED>

<!ATTLIST servos
driver CDATA #IMPLIED>

<!ATTLIST commands>
<!ATTLIST rc_commands>
<!ATTLIST ap_only_commands>
<!ATTLIST command_laws>

<!ATTLIST heli_curves>

<!ATTLIST section
name CDATA #IMPLIED
prefix CDATA #IMPLIED>

<!ATTLIST servo
name CDATA #REQUIRED
no CDATA #REQUIRED
min CDATA #REQUIRED
neutral CDATA #REQUIRED
max CDATA #REQUIRED>

<!ATTLIST curve
throttle CDATA #REQUIRED
rpm CDATA #IMPLIED
collective CDATA #REQUIRED>

<!ATTLIST axis
name CDATA #REQUIRED
failsafe_value CDATA #REQUIRED
group CDATA #IMPLIED>

<!ATTLIST set
value CDATA #REQUIRED
command CDATA #IMPLIED
servo CDATA #IMPLIED>

<!ATTLIST call
fun CDATA #REQUIRED>

<!ATTLIST copy
command CDATA #REQUIRED>

<!ATTLIST let
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST ratelimit
var CDATA #REQUIRED
value CDATA #REQUIRED
rate_min CDATA #REQUIRED
rate_max CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
unit CDATA #IMPLIED
code_unit CDATA #IMPLIED
integer CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST field
name CDATA #IMPLIED
value CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED
description CDATA #IMPLIED>

<!ATTLIST modules
main_freq CDATA #IMPLIED
target CDATA #IMPLIED>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED
dir CDATA #IMPLIED>

<!ATTLIST item
name CDATA #REQUIRED
type (checkbox|text|choice|number) "checkbox"
optional (true|false) "false"
help CDATA #IMPLIED
remember (true|false) "false"
values CDATA #IMPLIED
unit CDATA #IMPLIED
min CDATA #IMPLIED
max CDATA #IMPLIED>

=== paparazzi/paparazzi/conf/airframes/ENAC/quadrotor/djIR.xml
<!DOCTYPE airframe SYSTEM "../../airframe.dtd">

<airframe name="octIR">

  <description>
    * Autopilot:   TawakiV2
    * Actuators:   4 in 1  
    * Telemetry:   datalink
    * GPS:         datalink
    * RC:          datalink
  </description>

  <firmware name="rotorcraft">
    <configure name="RTOS_DEBUG" value="FALSE"/>
    <configure name="PERIODIC_FREQUENCY" value="500"/>
    <configure name="AHRS_PROPAGATE_FREQUENCY" value="$(PERIODIC_FREQUENCY)"/>

    <target name="ap" board="tawaki_2.0">
      <module name="radio_control" type="sbus"/>
      <define name="RADIO_KILL_SWITCH" value="RADIO_GAIN1"/>

      <configure name="BARO_PERIODIC_FREQUENCY" value="50"/>

      <configure name="ACCEL_AAF" value="126"/>
      <configure name="GYRO_AAF" value="441"/>
    </target>

    <target name="nps" board="pc">
      <module name="fdm" type="jsbsim"/>
      <module name="radio_control" type="ppm"/>
      <define name="TAWAKIV2_IMU_ROT" value=""/>
      <define name="TAWAKIV2_MAG_ROT" value=""/>
    </target>
    
    <module name="board" type="tawaki_2.0"/>
    
    <module name="telemetry" type="xbee_api"/>


    <module name="actuators" type="dshot">
      <configure name="DSHOT_BIDIR" value="FALSE"/>
    </module>

    <module name="gps" type="ublox">
      <configure name="UBX_GPS_BAUD" value="B230400"/>
    </module>

    <module name="stabilization" type="indi"/>
    <module name="guidance" type="indi"/>

    <module name="ins" type="ekf2">
      <configure name="USE_ALT_LLA_WAYPOINTS" value="FALSE"/>
      <define name="INS_EKF2_FORCE_NAV_REF" value="TRUE"/>
    </module>
    <!--module name="ins" type="ext_pose"/-->

    <module name="flight_recorder"/>
    <module name="logger_control_effectiveness">
      <define name="LOGGER_CONTROL_EFFECTIVENESS_ACTUATORS" value="TRUE"/>
    </module>

    <module name="thermal_ctl">
      <configure name="EXTRA_DL_PORT" value="UART3"/>
      <configure name="EXTRA_DL_BAUD" value="B115200"/>
    </module>

  </firmware>

  <servos driver="DShot">
    <servo name="FR" no="3" min="0" neutral="100" max="2000"/>
    <servo name="BR" no="4" min="0" neutral="100" max="2000"/>
    <servo name="BL" no="1" min="0" neutral="100" max="2000"/>
    <servo name="FL" no="2" min="0" neutral="100" max="2000"/>
  </servos>

  <commands>
    <axis name="FR" failsafe_value="MOTOR_STOP"/>
    <axis name="BR" failsafe_value="MOTOR_STOP"/>
    <axis name="BL" failsafe_value="MOTOR_STOP"/>
    <axis name="FL" failsafe_value="MOTOR_STOP"/>
    <axis name="THRUST" failsafe_value="0"/>
  </commands>

  <command_laws>
    <set servo="FR" value="@FR"/>
    <set servo="BR" value="@BR"/>
    <set servo="BL" value="@BL"/>
    <set servo="FL" value="@FL"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <define name="ACCEL_CALIB" type="array">
      <field type="struct">
        <field name="abi_id" value="24"/>
        <field name="calibrated" type="struct">
          <field name="neutral" value="true"/>
          <field name="scale_f" value="true"/>
          <field name="rotation" value="true"/>
        </field>
        <field name="neutral" value="-5,6,14" type="int[]"/>
        <field name="scale_f" value="{ 2.4470, 2.4541, 2.4551 }"/>
        <field value="TAWAKIV2_IMU_ROT"/>
      </field>
    </define>
    <define name="GYRO_CALIB" type="array">
      <field type="struct">
        <field name="abi_id" value="24"/>
        <field name="calibrated" type="struct">
          <field name="neutral" value="false"/>
          <field name="scale" value="false"/>
          <field name="rotation" value="true"/>
        </field>
        <field value="TAWAKIV2_IMU_ROT"/>
      </field>
    </define>
    <define name="MAG_CALIB" type="array">
      <field type="struct">
        <field name="abi_id" value="3"/>
        <field name="calibrated" type="struct">
          <field name="neutral" value="true"/>
          <field name="scale_f" value="true"/>
          <field name="rotation" value="true"/>
        </field>
        <field name="neutral" value="-2677,3223,-3142" type="int[]"/>
        <field name="scale_f" value="{ 0.6654, 0.6802, 0.6746 }"/>
        <field value="TAWAKIV2_MAG_ROT"/>
      </field>
    </define>

    <define name="BODY_TO_IMU_PHI" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_PSI" value="180." unit="deg"/>
  </section>

  <section name="STABILIZATION_ATTITUDE" prefix="STABILIZATION_ATTITUDE_">
    <!-- setpoint limits for attitude stabilization rc flight -->
    <define name="SP_MAX_PHI" value="45" unit="deg"/>
    <define name="SP_MAX_THETA" value="45" unit="deg"/>
    <define name="SP_MAX_R" value="60" unit="deg/s"/>
    <define name="DEADBAND_A" value="0"/>
    <define name="DEADBAND_E" value="0"/>
    <define name="DEADBAND_R" value="50"/>
  </section>

  <section name="STABILIZATION_ATTITUDE_INDI" prefix="STABILIZATION_INDI_">
    <define name="NUM_ACT" value="4"/>
    <!-- reference acceleration for attitude control -->
    <define name="REF_ERR_P" value="120"/>
    <define name="REF_ERR_Q" value="120"/>
    <define name="REF_ERR_R" value="120"/>
    <define name="REF_RATE_P" value="17"/>
    <define name="REF_RATE_Q" value="17"/>
    <define name="REF_RATE_R" value="10"/>
    <define name="MAX_R" value="45" unit="deg/s"/>

    <!-- second order filter parameters -->
    <define name="FILT_CUTOFF" value="4.0"/>
    <define name="FILT_CUTOFF_R" value="4.0"/>

    <!-- Adaptive Learning Rate -->
    <define name="USE_ADAPTIVE" value="FALSE"/>
    <define name="ADAPTIVE_MU" value="0.0001"/>

    <define name="COMMANDS" value="{COMMAND_FR, COMMAND_BR, COMMAND_BL, COMMAND_FL}"/>

    <!-- Full INDI -->
    <!-- control effectiveness -->
    <define name="G1" type="matrix">
      <field value="-30.42, -28.45, 31.37, 32.02" type="float[]"/>
      <field value="31.27, -25.46, -31.53, 27.11" type="float[]"/>
      <field value="1.98, -2.22, 1.48, -3.07" type="float[]"/>
      <field value="-1.27, -1.06, -0.83, -0.68" type="float[]"/>
    </define>
    <!--Counter torque effect of spinning up a rotor-->
    <define name="G2" value="{195.20, -249.16, 218.79, -178.50}"/>
    <!-- first order actuator dynamics -->
    <define name="ACT_FREQ" value="{13.6, 13.6, 13.6, 13.6}"/>
    <define name="ESTIMATION_FILT_CUTOFF" value="4.0"/>
    <!--Priority for each axis (roll, pitch, yaw and thrust)-->
    <define name="WLS_PRIORITIES" value="{1000, 1000, 1, 100}"/>
  </section>

  <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
    <define name="REF_MIN_ZDD" value="-0.4*9.81"/>
    <define name="REF_MAX_ZDD" value=" 0.4*9.81"/>
    <define name="REF_MIN_ZD" value="-2."/>
    <define name="REF_MAX_ZD" value=" 2."/>
    <define name="NOMINAL_HOVER_THROTTLE" value="0.35"/>
  </section>

  <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
    <define name="MAX_BANK" value="30" unit="deg"/>
    <define name="REF_MAX_SPEED" value="0.5"/>
    <define name="REF_MAX_ACCEL" value="2."/>
  </section>

  <section name="GUIDANCE_INDI" prefix="GUIDANCE_INDI_">
    <!--define name="POS_GAIN" value="0.8"/>
    <define name="SPEED_GAIN" value="1.4"/-->
  </section>

  <section name="NAV">
    <define name="ARRIVED_AT_WAYPOINT" value="0.6"/>
    <define name="NAV_CLIMB_VSPEED" value="0.8"/>
    <define name="NAV_DESCEND_VSPEED" value="-0.5"/>
  </section>

  <section name="BAT">
    <define name="CATASTROPHIC_BAT_LEVEL" value="6.4" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="6.8" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="7.2" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="8.4" unit="V"/>
    <define name="BAT_NB_CELLS" value="2"/>
  </section>

  <section name="AUTOPILOT">
    <define name="MODE_STARTUP" value="AP_MODE_NAV"/>
    <define name="MODE_MANUAL" value="AP_MODE_ATTITUDE_DIRECT"/>
    <define name="MODE_AUTO1" value="AP_MODE_GUIDED"/>
    <define name="MODE_AUTO2" value="AP_MODE_NAV"/>
    <define name="FAILSAFE_FIXED_THROTTLE" value="0.1*MAX_PPRZ"/>
  </section>

  <section name="GCS">
    <define name="ALT_SHIFT_PLUS_PLUS" value="3"/>
    <define name="ALT_SHIFT_PLUS" value="1"/>
    <define name="ALT_SHIFT_MINUS" value="-0.5"/>
  </section>

  <section name="SIMULATOR" prefix="NPS_">
    <define name="ACTUATOR_NAMES" value="ne_motor, se_motor, sw_motor, nw_motor" type="string[]"/>
    <define name="JSBSIM_MODEL" value="simple_x_quad_ccw" type="string"/>
    <define name="COMMANDS_NB" value="4"/>
    <define name="NO_MOTOR_MIXING" value="TRUE"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/untested/examples/easystar.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<!--
    Multiplex EasyStar, using rudder
    TWOG v1 board
    Tilted infrared sensor
    XBee 2.4GHz modem in transparent mode
-->

<airframe name="EasyStar TWOGv1">

  <firmware name="fixedwing">
    <target name="ap" 			board="twog_1.0"/>
    <target name="sim" 			board="pc"/>

    <define name="LOITER_TRIM"/>

    <subsystem name="radio_control" type="ppm"/>
    <subsystem name="telemetry" type="transparent"/>
    <subsystem name="control"/>
    <subsystem name="gps" type="ublox"/>
    <subsystem name="navigation"/>
    <subsystem name="ins" type="alt_float"/>
  </firmware>

  <firmware name="setup">
    <target name="tunnel" 		board="twog_1.0"/>
  </firmware>

  <modules>
    <load name="infrared_adc.xml"/>
    <load name="ahrs_infrared.xml"/>
  </modules>

<!-- commands section -->
  <servos>
    <servo name="THROTTLE"      no="7" min="1120" neutral="1120" max="1920"/>
    <servo name="ELEVATOR"      no="3" min="1100" neutral="1515" max="1900"/>
    <servo name="RUDDER"        no="4" min="950" neutral="1440" max="2050"/>
  </servos>

  <commands>
    <axis name="THROTTLE" failsafe_value="0"/>
    <axis name="ROLL"     failsafe_value="0"/>
    <axis name="PITCH"    failsafe_value="0"/>
  </commands>

  <rc_commands>
    <set command="ROLL"      value="@ROLL"/>
    <set command="PITCH"     value="@PITCH"/>
    <set command="THROTTLE"  value="@THROTTLE"/>
  </rc_commands>

  <command_laws>
    <set servo="THROTTLE"    value="@THROTTLE"/>
    <set servo="RUDDER"      value="@ROLL"/>
    <set servo="ELEVATOR"    value="@PITCH"/>
  </command_laws>

  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="50" unit="deg"/>
    <define name="MAX_PITCH" value="40" unit="deg"/>
  </section>

  <section name="INFRARED" prefix="IR_">
    <define name="ADC_IR1_NEUTRAL" value="512"/>
    <define name="ADC_IR2_NEUTRAL" value="510"/>
    <define name="ADC_TOP_NEUTRAL" value="500"/>

    <define name="LATERAL_CORRECTION" value="0.7"/>
    <define name="LONGITUDINAL_CORRECTION" value="0.7"/>
    <define name="VERTICAL_CORRECTION" value="1."/>

    <define name="HORIZ_SENSOR_TILTED" value="1"/>
    <define name="IR1_SIGN" value="1"/>
    <define name="IR2_SIGN" value="-1"/>
    <define name="TOP_SIGN" value="1"/>

    <define name="ROLL_NEUTRAL_DEFAULT" value="-5.3" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="-3" unit="deg"/>

    <define name="CORRECTION_UP" value="1."/>
    <define name="CORRECTION_DOWN" value="1."/>
    <define name="CORRECTION_LEFT" value="1."/>
    <define name="CORRECTION_RIGHT" value="1."/>
  </section>


  <section name="BAT">
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="20000" unit="mA"/>
    <define name="CATASTROPHIC_BAT_LEVEL" value="8.0" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="8.5" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="9.5" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="12.5" unit="V"/>
  </section>

  <section name="MISC">
    <define name="NOMINAL_AIRSPEED" value="15." unit="m/s"/>
    <define name="CARROT" value="4." unit="s"/>
    <define name="KILL_MODE_DISTANCE" value="(2.0*MAX_DIST_FROM_HOME)"/>
    <define name="CONTROL_FREQUENCY" value="60" unit="Hz"/>
    <define name="NO_XBEE_API_INIT" value="TRUE"/>
    <define name="TRIGGER_DELAY" value="1."/>
    <define name="DEFAULT_CIRCLE_RADIUS" value="100."/>
  </section>

  <section name="VERTICAL CONTROL" prefix="V_CTL_">
    <define name="POWER_CTL_BAT_NOMINAL" value="11.0" unit="volt"/>
    <!-- outer loop -->
    <define name="ALTITUDE_PGAIN" value="0.075" unit="(m/s)/m"/>
    <define name="ALTITUDE_MAX_CLIMB" value="4." unit="m/s"/>
    <!-- auto throttle inner loop -->
    <define name="AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE" value="0.5" unit="%"/>
    <define name="AUTO_THROTTLE_MIN_CRUISE_THROTTLE" value="0.4" unit="%"/>
    <define name="AUTO_THROTTLE_MAX_CRUISE_THROTTLE" value="0.8" unit="%"/>
    <define name="AUTO_THROTTLE_LOITER_TRIM" value="1500" unit="pprz_t"/>
    <define name="AUTO_THROTTLE_DASH_TRIM" value="-1000" unit="pprz_t"/>
    <define name="AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT" value="0.1" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_PGAIN" value="0.02" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_IGAIN" value="0.1"/>
    <define name="AUTO_THROTTLE_PITCH_OF_VZ_PGAIN" value="0.05" unit="rad/(m/s)"/>
    <define name="AUTO_PITCH_PGAIN" value="0.125"/>
    <define name="AUTO_PITCH_IGAIN" value="0.025"/>
    <define name="AUTO_PITCH_MAX_PITCH" value="RadOfDeg(25)"/>
    <define name="AUTO_PITCH_MIN_PITCH" value="RadOfDeg(-25)"/>
    <define name="THROTTLE_SLEW" value="1.0"/>
  </section>

  <section name="HORIZONTAL CONTROL" prefix="H_CTL_">
    <define name="COURSE_PGAIN" value="0.7"/>
    <define name="ROLL_MAX_SETPOINT" value="35" unit="deg"/>
    <define name="PITCH_MAX_SETPOINT" value="25" unit="deg"/>
    <define name="PITCH_MIN_SETPOINT" value="-25" unit="deg"/>
    <define name="PITCH_PGAIN" value="20000."/>
    <define name="PITCH_DGAIN" value="1.5"/>
    <define name="ELEVATOR_OF_ROLL" value="2500"/>
    <define name="ROLL_ATTITUDE_GAIN" value="7400"/>
    <define name="ROLL_RATE_GAIN" value="200"/>
  </section>

  <section name="NAV">
    <define name="NAV_GLIDE_PITCH_TRIM" value="0"/>
  </section>

  <section name="AGGRESSIVE" prefix="AGR_">
    <define name="BLEND_START" value="20"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="10"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_THROTTLE" value="0.9"/><!-- Gaz for Aggressive Climb -->
    <define name="CLIMB_PITCH" value="RadOfDeg(18)"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_THROTTLE" value="0.1"/><!-- Gaz for Aggressive Decent -->
    <define name="DESCENT_PITCH" value="RadOfDeg(-20)"/><!-- Pitch for Aggressive Decent -->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
  </section>

  <section name="FAILSAFE" prefix="FAILSAFE_">
    <define name="DELAY_WITHOUT_GPS" value="3" unit="s"/>
    <define name="DEFAULT_THROTTLE" value="0.4" unit="%"/>
    <define name="DEFAULT_ROLL" value="15" unit="deg"/>
    <define name="DEFAULT_PITCH" value="0" unit="deg"/>
    <define name="HOME_RADIUS" value="90" unit="m"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/ENAC/swarm/calibrations/disco_61.xml
<!DOCTYPE airframe SYSTEM "../../../airframe.dtd">

<airframe>
  <servos>
    <servo name="MOTOR" no="0" min="1000" neutral="1000" max="12500"/>
    <servo name="AILEVON_RIGHT" no="6" min="1900" neutral="1396" max="1100"/>
    <servo name="AILEVON_LEFT" no="1" min="1100" neutral="1548" max="1900"/>
  </servos>

  <section name="IMU" prefix="IMU_">
    <define name="ACCEL_CALIB" type="array">
      <field type="struct">
        <field name="abi_id" value="1"/>
        <field name="calibrated" type="struct">
          <field name="neutral" value="true"/>
          <field name="scale_f" value="true"/>
        </field>
        <field name="neutral" value="-193,12,-296" type="int[]"/>
        <field name="scale_f" value="{ 2.4430, 2.4542, 2.4194 }"/>
      </field>
    </define>
    <define name="MAG_CALIB" type="array">
      <field type="struct">
        <field name="abi_id" value="1"/>
        <field name="calibrated" type="struct">
          <field name="neutral" value="true"/>
          <field name="scale_f" value="true"/>
        </field>
        <field name="neutral" value="-164,-244,-590" type="int[]"/>
        <field name="scale_f" value="{ 7.762686, 7.537779, 8.130335 }"/>
      </field>
    </define>
  </section>
</airframe>

=== paparazzi/paparazzi/conf/airframes/untested/hex_naze32.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<!-- this is a test file for the Abusemark Naze32 rev5 board:
     * Autopilot:   Abusemark Naze32       https://code.google.com/p/afrodevices/wiki/AfroFlight32
     * Actuators:   PWM motor controllers  http://wiki.paparazziuav.org/wiki/Subsystem/actuators#PWM
     * RC:          PPM input              http://wiki.paparazziuav.org/wiki/Subsystem/radio_control#PPM

     hex copter configuration (USE_SERVOS_5AND6) moves the PPM input from "1" to "6" on RC input
     pwm motor connectors are in "standard mode" M1-M6 on the servo headers
-->

<airframe name="Hexcopter Naze32">

  <firmware name="rotorcraft">
    <define name="PPRZ_TRIG_INT_COMPR_FLASH"/>
    <define name="PPRZ_TRIG_INT_COMPR_HIGHEST"/>
    <target name="ap" board="naze32_rev5">
    </target>

    <subsystem name="radio_control" type="ppm"/>

    <subsystem name="motor_mixing"/>
    <subsystem name="actuators"     type="pwm">
      <define name="SERVO_HZ" value="400"/>
    </subsystem>

    <subsystem name="telemetry"     type="transparent"/>
    <subsystem name="imu"           type="mpu60x0_i2c">
      <configure name="IMU_MPU60X0_I2C_DEV" value="i2c2"/>
      <configure name="USE_MAGNETOMETER" value="FALSE"/>
    </subsystem>
    <subsystem name="stabilization" type="int_quat"/>
    <subsystem name="ahrs"          type="int_cmpl_quat">
      <define name="AHRS_GRAVITY_HEURISTIC_FACTOR" value="30"/>
    </subsystem>
    <subsystem name="ins"/>
    <subsystem name="gps"           type="ublox"/>
  </firmware>

  <firmware name="test_progs">
    <target name="test_sys_time_timer" board="naze32_rev5"/>
    <target name="test_sys_time_usleep" board="naze32_rev5"/>
    <target name="test_telemetry" board="naze32_rev5"/>
    <target name="test_math_trig_lut" board="naze32_rev5"/>
    <target name="test_imu" board="naze32_rev5">
      <subsystem name="imu" type="mpu6000"/>
    </target>
    <target name="test_ahrs" board="naze32_rev5">
      <subsystem name="imu" type="mpu6000"/>
      <subsystem name="ahrs" type="int_cmpl_quat"/>
      <configure name="USE_MAGNETOMETER" value="FALSE"/>
    </target>
  </firmware>

  <modules>
    <load name="mag_hmc58xx.xml">
      <define name="MODULE_HMC58XX_UPDATE_AHRS"/>
      <configure name="MAG_HMC58XX_I2C_DEV" value="i2c2"/>
    </load>
    <load name="gps_ubx_ucenter.xml"/>
  </modules>

  <servos driver="Pwm">
    <!-- Naze32 Hexa-X standard -->
    <servo name="BACK_RIGHT"   no="0" min="1000" neutral="1100" max="1900"/>
    <servo name="FRONT_RIGHT"  no="1" min="1000" neutral="1100" max="1900"/>
    <servo name="BACK_LEFT"    no="2" min="1000" neutral="1100" max="1900"/>
    <servo name="FRONT_LEFT"   no="3" min="1000" neutral="1100" max="1900"/>
    <servo name="CENTER_RIGHT" no="4" min="1000" neutral="1100" max="1900"/>
    <servo name="CENTER_LEFT"  no="5" min="1000" neutral="1100" max="1900"/>
  </servos>

  <commands>
    <axis name="ROLL"   failsafe_value="0"/>
    <axis name="PITCH"  failsafe_value="0"/>
    <axis name="YAW"    failsafe_value="0"/>
    <axis name="THRUST" failsafe_value="0"/>
  </commands>

  <section name="MIXING" prefix="MOTOR_MIXING_">
    <define name="TRIM_ROLL" value="0"/>
    <define name="TRIM_PITCH" value="0"/>
    <define name="TRIM_YAW" value="0"/>
    <define name="NB_MOTOR" value="6"/>
    <define name="SCALE" value="256"/>
    <!-- https://github.com/gearwolf-OP/Mini-Hexacopter >
    <    Naze32 Hexa-X standard        BR_CC FR_CC  BL_C  FL_C  CR_C CL_CC  -->
    <define name="ROLL_COEF"   value="{ 106,  150, -106, -150,  256, -256}"/>
    <define name="PITCH_COEF"  value="{-256,  256, -256,  256,    0,    0}"/>
    <define name="YAW_COEF"    value="{ 199,  192, -199, -192, -256,  256}"/>
    <define name="THRUST_COEF" value="{ 256,  256,  256,  256,  256,  256}"/>
  </section>

  <command_laws>
    <call fun="motor_mixing_run(autopilot_motors_on,FALSE,values)"/>
    <set servo="BACK_RIGHT"   value="motor_mixing.commands[0]"/>
    <set servo="FRONT_RIGHT"  value="motor_mixing.commands[1]"/>
    <set servo="BACK_LEFT"    value="motor_mixing.commands[2]"/>
    <set servo="FRONT_LEFT"   value="motor_mixing.commands[3]"/>
    <set servo="CENTER_RIGHT" value="motor_mixing.commands[4]"/>
    <set servo="CENTER_LEFT"  value="motor_mixing.commands[5]"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <define name="BODY_TO_IMU_PHI"   value="180." unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_PSI"   value="0." unit="deg"/>
  </section>

  <section name="STABILIZATION_RATE" prefix="STABILIZATION_RATE_">
    <!-- setpoints -->
    <define name="SP_MAX_P" value="140" unit="deg/s"/>
    <define name="SP_MAX_Q" value="140" unit="deg/s"/>
    <define name="SP_MAX_R" value="140" unit="deg/s"/>
    <define name="DEADBAND_P" value="20"/>
    <define name="DEADBAND_Q" value="20"/>
    <define name="DEADBAND_R" value="200"/>
    <define name="REF_TAU" value="4"/>

    <!-- feedback -->
    <define name="GAIN_P" value="400"/>
    <define name="GAIN_Q" value="400"/>
    <define name="GAIN_R" value="350"/>

    <define name="IGAIN_P" value="75"/>
    <define name="IGAIN_Q" value="75"/>
    <define name="IGAIN_R" value="50"/>

    <!-- feedforward -->
    <define name="DDGAIN_P" value="300"/>
    <define name="DDGAIN_Q" value="300"/>
    <define name="DDGAIN_R" value="300"/>
  </section>


  <section name="STABILIZATION_ATTITUDE" prefix="STABILIZATION_ATTITUDE_">
    <!-- setpoints -->
    <define name="SP_MAX_PHI"     value="45." unit="deg"/>
    <define name="SP_MAX_THETA"   value="45." unit="deg"/>
    <define name="SP_MAX_R"       value="90." unit="deg/s"/>
    <define name="DEADBAND_A"     value="0"/>
    <define name="DEADBAND_E"     value="0"/>
    <define name="DEADBAND_R"     value="250"/>

    <!-- reference -->
    <define name="REF_OMEGA_P"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_P"   value="0.85"/>
    <define name="REF_MAX_P"    value="400." unit="deg/s"/>
    <define name="REF_MAX_PDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_Q"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_Q"   value="0.85"/>
    <define name="REF_MAX_Q"    value="400." unit="deg/s"/>
    <define name="REF_MAX_QDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_R"  value="250" unit="deg/s"/>
    <define name="REF_ZETA_R"   value="0.85"/>
    <define name="REF_MAX_R"    value="180." unit="deg/s"/>
    <define name="REF_MAX_RDOT" value="RadOfDeg(1800.)"/>

    <!-- feedback -->
    <define name="PHI_PGAIN"  value="1000"/>
    <define name="PHI_DGAIN"  value="400"/>
    <define name="PHI_IGAIN"  value="200"/>

    <define name="THETA_PGAIN"  value="1000"/>
    <define name="THETA_DGAIN"  value="400"/>
    <define name="THETA_IGAIN"  value="200"/>

    <define name="PSI_PGAIN"  value="500"/>
    <define name="PSI_DGAIN"  value="300"/>
    <define name="PSI_IGAIN"  value="10"/>

    <!-- feedforward -->
    <define name="PHI_DDGAIN"   value="300"/>
    <define name="THETA_DDGAIN" value="300"/>
    <define name="PSI_DDGAIN"   value="300"/>
  </section>

  <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
    <define name="HOVER_KP"    value="150"/>
    <define name="HOVER_KD"    value="80"/>
    <define name="HOVER_KI"    value="20"/>
    <define name="NOMINAL_HOVER_THROTTLE" value="0.5"/>
    <define name="ADAPT_THROTTLE_ENABLED" value="TRUE"/>
  </section>

  <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
    <define name="MAX_BANK" value="20" unit="deg"/>
    <define name="USE_SPEED_REF" value="TRUE"/>
    <define name="PGAIN" value="50"/>
    <define name="DGAIN" value="100"/>
    <define name="AGAIN" value="70"/>
    <define name="IGAIN" value="20"/>
  </section>

  <section name="AUTOPILOT">
    <define name="MODE_MANUAL" value="AP_MODE_RATE_DIRECT"/>
    <define name="MODE_AUTO1"  value="AP_MODE_ATTITUDE_DIRECT"/>
    <define name="MODE_AUTO2"  value="AP_MODE_HOVER_Z_HOLD"/>
  </section>

  <section name="BAT">
    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="9.6" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="10.1" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="12.4" unit="V"/>
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="30000"/>
  </section>

</airframe>
